Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: paw-99-datalake
  SampleBucketPolicy:
    DependsOn: S3Bucket
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          -
            Sid: ReadWrite
            Action: "*"
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "S3Bucket"
                  - "/*"
            Principal: "*"

  LakeFormationLocation:
    DependsOn: S3Bucket
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        Fn::GetAtt:
          - S3Bucket
          - Arn
      RoleArn:
        Fn::Join:
          - ':'
          - - "arn:aws:iam:"
            - !Ref AWS::AccountId
            - role/aws-service-role/lakeformation.amazonaws.com/AWSServiceRoleForLakeFormationDataAccess
      UseServiceLinkedRole: true
