Resources:
  FlaskAppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "flask_app"
      ImageScanningConfiguration:
        scanOnPush: true
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - Fn::Join:
                    - ':'
                    - - "arn:aws:iam:"
                      - Ref: AWS::AccountId
                      - "user/cli_user"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
Outputs:
  FlaskAppRepositoryArn:
    Value:
      Fn::GetAtt: FlaskAppRepository.Arn
  FlaskAppRepositoryName:
    Value:
      Ref: FlaskAppRepository
