Resources:
  s3bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  firehosePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: firehose-policy
      Roles:
        - Ref: firehoseRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: s3bucket
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: s3bucket
                  - '*'
  firehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: firehose-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
  firehoseStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: MyLogStream
      S3DestinationConfiguration:
        BucketARN:
          Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: s3bucket
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 5
        CompressionFormat: UNCOMPRESSED
        ErrorOutputPrefix: firehose_error/
        Prefix: firehose/
        RoleARN:
          Fn::GetAtt:
            - firehoseRole
            - Arn
